project:
  type: website
  output-dir: docs

website:
  title: "2024 Open Source Survey Results"
  favicon: images/favicon.ico
  page-navigation: TRUE
  navbar:
    logo: images/header-logo.png
    right:
      - icon: github
        href: https://github.com/UW-Madison-DSI/open_source_survey_results
        aria-label: GitHub
  sidebar:
    style: "floating"
  page-footer:
    background: dark
    left: UW-Madison Open Source Survey Results [{{< fa brands github title="GitHub octocat logo" >}}](https://github.com/UW-Madison-DSI/open_source_survey_results){target=_blank}
    right: This website is built with [Quarto](https://quarto.org/){target=_blank} by UW-Madison’s [Open Source Program Office](https://ospo.wisc.edu/) and [Data Science Institute](https://datascience.wisc.edu/institute/)
    
execute:
  echo: false
  message: false
  warning: false

metadata-files:
  - sidebar.yml

format:
  html:
    theme: [default, custom.scss]
    toc: true
    mainfont: Red Hat Text



