---
title: "Home"
---

<!-- Setup -->

```{r}
source('setup.R')
```

Thanks to a grant from the [Alfred P. Sloan Foundation](https://sloan.org/), The [University of Wisconsin–Madison Open Source Program Office](https://ospo.wisc.edu/) (OSPO) is positioned to support and grow our vibrant open source ecosystem. The OSPO’s mission is to collaborate with key stakeholders and community members to provide open source learning opportunities, promote best practices, facilitate the use of open source software in research, and make open source–fueled connections between practitioners and adopters on campus and beyond.

In Spring 2024, the OSPO distributed an open source survey to gauge the usage of open source tools among members of the university community, identify open source projects under development, and to collect feedback on improving the open source environment at UW-Madison. This site summarizes the findings of the results and allows users to explore how campus community members use open source tools at `r uni_name`.

</br>
<center>
[View the results](sample.qmd){.btn} 
</center>
</br>

We are open sourcing [the survey itself](https://github.com/UW-Madison-DSI/open_source_survey_results/blob/main/Open_Source_Program_Office_Survey.qsf) (in Qualtrics format), an [anonymized version of the responses](https://github.com/UW-Madison-DSI/open_source_survey_results/blob/main/data/survey_data.csv), and this Quarto-based analysis of the survey results. Our goal is to streamline such surveys at other universities and encourage a uniform set of questions and responses that can more easily be aggregated to understand the broader open source ecosystem in academia. If you're interested in recreating this survey and website for your institution please see the [reproduction section](reproduction.qmd).

We have a companion [Site](https://uw-madison-dsi.github.io/open_source_survey_results_myst/) built in Python.
